---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ee-helloworld
  name: ee-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ee-helloworld
  strategy: {}
  template:
    metadata:
      labels:
        app: ee-helloworld
    spec:
      containers:
      - image: kamalperumal/hello_world:v0.0.2
        name: ee-helloworld
        ports:
        - containerPort: 8080
           